language: python
dist: trusty
# Apparently we need sudo to add the ubuntugis ppa
sudo: true
python: 2.7
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
  addons:
    postgresql: "9.4"
env:
  global:
      - PDP_CONFIG=$TRAVIS_BUILD_DIR/pdp/config.yaml
      - CPLUS_INCLUDE_PATH=/usr/include/gdal
      - C_INCLUDE_PATH=/usr/include/gdal
      - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple
before_install:
  # Travis's apt-sources addon seems to be broken for the ubuntugis PPA
  # Install it manually
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install libgdal-dev -y
install:
    # upgrade pip to be able to resolve the h5py/Cython co-deps
    # https://github.com/h5py/h5py/issues/535#issuecomment-119546308
    - pip install -U pip
    - pip install -r requirements.txt -r test_requirements.txt -r deploy_requirements.txt
    - pip install .
script:
    - py.test -vv --tb=short -m "not crmpdb and not bulk_data" tests
    - flake8
