language: python
python: 2.7_with_system_site_packages
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-gdal python-numpy libhdf5-serial-dev libnetcdf-dev
install:
    - pip install -i https://pypi.pacificclimate.org/simple/ -r requirements.txt -r test_requirements.txt
    - pip install -i https://pypi.pacificclimate.org/simple/ .
script:
    - py.test -vv --tb=short -m "not crmpdb and not bulk_data" tests
