app_root: 'https://tools.pacificclimate.org/dataportal'
data_root: 'https://tools.pacificclimate.org/dataportal/data'
title: ''
ensemble_name: ''
dsn: postgresql://httpd_meta@atlas.pcic/pcic_meta # add password for production
pcds_dsn: postgresql://httpd@atlas.pcic/crmp # add password for production
js_min: false
geoserver_url: https://atlas.pcic.uvic.ca/geoserver/ # change for production
ncwms_url: 
    - https://atlas.pcic.uvic.ca/ncWMS/wms # change for production
tilecache_url: 
    - http://tiles.pacificclimate.org/tilecache/tilecache.py
use_auth: True
session_dir: default
clean_session_dir: True # change for production
use_analytics: True
analytics: UA-20166041-3 # change for production
